name: Unit Test

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

permissions:
  checks: write

jobs:
  unit:
    name: ${{ inputs.service }}
    runs-on: self-hosted
    container:
      image: reneruprecht/ci-java21jdk
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ inputs.service }}-${{ hashFiles(format('{0}/pom.xml', inputs.service)) }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ inputs.service }}

      - name: Unit tests
        working-directory: ${{ inputs.service }}
        run: |
          ./mvnw -B -ntp -e test

      - name: Unit test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: ${{ inputs.service }}/target/surefire-reports/*.xml
          check_name: ${{inputs.service }} Unit Tests
