name: Integration Test

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  integration:
    name: ${{ inputs.service }}
    runs-on: self-hosted
    container:
      image: reneruprecht/ci-java21jdk
    env:
      SPRING_PROFILES_ACTIVE: test
      SPRING_COMPOSE_ENABLED: false
      POSTGRES_HOST: "postgres_test"
      POSTGRES_DB: "test"
      POSTGRES_PORT: "5432"
      KAFKA_BROKER_SERVER: "broker"
      KAFKA_BROKER_SERVER_PORT: "9092"
    services:
      postgres_test:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: "myuser"
          POSTGRES_PASSWORD: "secret"
          POSTGRES_DB: "test"
        options: >- 
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

      broker:
        image: apache/kafka:latest
        options: >- 
          --health-cmd "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list && break"
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_NUM_PARTITIONS: 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ inputs.service }}-${{ hashFiles(format('{0}/pom.xml', inputs.service)) }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ inputs.service }}

      - name: Clean
        working-directory: ${{ inputs.service }}
        run: |
          ./mvnw clean

      - name: Integration tests
        working-directory: ${{ inputs.service }}
        run: |
          ./mvnw -B -ntp -e verify

      - name: Integration test report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: ${{ inputs.service }}/target/failsafe-reports/TEST-*.xml
          check_name: ${{ inputs.service }} Integration Tests

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ${{ inputs.service }}/target/site/jacoco/jacoco.csv
