name: Backend

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  unit-test:
    uses: ./.github/workflows/backend-unit-test.yml
    with:
      service: "${{ inputs.service }}"

