name: E2E

on:
  workflow_call:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Start docker + run E2E
        run: |
          docker compose -f compose.test.yaml up --build --abort-on-container-exit

      - name: Show logs (on failure)
        if: failure()
        run: docker compose -f compose.test.yaml logs

      - name: Cleanup
        if: always()
        run: docker compose -f compose.test.yaml down -v
