name: Main Branch

on:
  push:
    branches:
      - main

jobs:
  task-service:
    uses: ./.github/workflows/backend.yml
    with:
      service: "task-service"
    permissions:
      checks: write

