name: Main Branch

on:
  push:
    branches:
      - main

jobs:
  test-services:
    strategy:
      matrix:
        service:
          - task-service
          - user-service
    uses: ./.github/workflows/backend.yml
    with:
      service: ${{ matrix.service }}
    permissions:
      checks: write

  test-frontend:
    uses: ./.github/workflows/frontend.yml
    permissions:
      contents: read
      pull-requests: write
