name: Main Branch

on:
  push:
    branches:
      - main

jobs:
  backend-unit:
    name: "Backend Unit Tests"
    strategy:
      matrix:
        service:
          - task-service
          # - user-service
    uses: ./.github/workflows/backend-unit-test.yml
    with:
      service: ${{ matrix.service }}
    permissions:
      checks: write

  backend-integration:
    name: "Backend Integration Tests"
    needs: backend-unit
    strategy:
      matrix:
        service:
          - task-service
          # - user-service
    uses: ./.github/workflows/backend-integration-test.yml
    with:
      service: ${{ matrix.service }}
    permissions:
      checks: write

  # test-frontend:
  #   name: "Frontend"
  #   uses: ./.github/workflows/frontend.yml
  #   permissions:
  #     contents: read
  #     pull-requests: write
